services:

  app:
    container_name: kt-app
    build:
        context: .
        dockerfile: ./.devcontainer/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html

###> doctrine/doctrine-bundle ###
  database:
    container_name: kt-db
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: db
      MYSQL_PASSWORD: db
    ports:
      - "3306:3306"
    volumes:
      - database_data:/var/lib/mysql
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
