services:

    Ocebot\KujiraTrack\Fin\Domain\FinContractRepository:
        alias: Ocebot\KujiraTrack\Fin\Infrastructure\FinContractRepositoryInMemoryDev

    Ocebot\KujiraTrack\Fin\Domain\FinCandlesService:
        alias: Ocebot\KujiraTrack\Fin\Infrastructure\FinCandlesServiceLcdCached