services:
    Ocebot\KujiraTrack\FinContracts\Domain\FinContractRepository:
        alias: Ocebot\KujiraTrack\FinContracts\Infrastructure\FinContractRepositoryInMemoryDev
    Ocebot\KujiraTrack\FinContractCharts\Domain\FinContractCandlesService:
        alias: Ocebot\KujiraTrack\FinContractCharts\Infrastructure\FinContractCandlesServiceLcd