services:

    Ocebot\KujiraTrack\Fin\Domain\FinContractRepository:
        alias: Ocebot\KujiraTrack\FinContracts\Infrastructure\FinContractRepositoryInMemoryDev

    Ocebot\KujiraTrack\Fin\Domain\FinCandlesService:
        alias: Ocebot\KujiraTrack\FinCandles\Infrastructure\FinCandlesServiceLcdCached