services:
    Ocebot\KujiraTrack\FinContracts\Domain\FinContractRepository:
        alias: Ocebot\KujiraTrack\FinContracts\Infrastructure\FinContractRepositoryInMemoryDev
    Ocebot\KujiraTrack\FinCandles\Domain\FinCandlesService:
        alias: Ocebot\KujiraTrack\FinCandles\Infrastructure\FinCandlesServiceLcdCached