name: Build and deploy

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        id: build-files
        run: composer install --prefer-dist --no-progress

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Copy result in server
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --delete
          path: ./
          remote_path: ${{ secrets.KT_HOST_PATH }}
          remote_host: ${{ secrets.OCEBOT_HOST }}
          remote_user: ${{ secrets.OCEBOT_HOST_USER }}
          remote_key: ${{ secrets.OCEBOT_PRIVATE_SSH_KEY }}
    
